name: Commit list - DEV

on:
  push:
    branches:
      - dev

jobs:
  dev-list-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: joined the list
        run: |
          git fetch --unshallow || true
          git log --pretty=format:"%H - %an <%ae> - %s - %ad"
