name: STAGE-DEPLOY

on:
  push:
    branches: [stage]
jobs:
  stage-deploy:
    runs-on:
      group: Default
      labels: [self-hosted, Linux, x64, STAGE]
    environment:
      name: stage
      url: ''
    strategy:
      matrix:
        node-version: [lts/*]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install yarn
        run: npm i -g yarn

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: 'Create env file'
        run: |
          echo '${{ secrets.STAGE_ENV_FILE }}' > .env

      - name: prisma generate
        run: yarn gen

      - name: prisma generate schema
        run: yarn prisma generate --schema prisma/schema.prisma

      - name: prisma generate schema1
        run: yarn prisma generate --schema prisma/schema1.prisma

      - name: build
        run: yarn build

      - name: start or reload server
        run: pm2 startOrGracefulReload ecosystem.config.js
